### ISSUE TITLE
Octoprint1.3.8 : Webcam don't appear

### ISSUE THREAD

**Issue by jjtronics** [mikedmor/OctoPrint_MultiCam#1]
Hello,
Great idea this plugin!
I already have two webcams running on my octoprint 1.3.8 and I installed the latest version of MultiCam 0.2.1 But i have no window of visualization and only one webcam appears in control tab : 
https://www.dropbox.com/s/7ivp45ovb321qsv/Capture%20d%27%C3%A9cran%202018-05-10%2004.36.25.png?dl=0

I have two webcam in multicam parameters : https://www.dropbox.com/s/mc3cczddxt082yq/Capture%20d%27%C3%A9cran%202018-05-10%2004.35.34.png?dl=0

and in my .octoprint/config.yaml , i have : 
  multicam:
    multicam_profiles:
    - URL: /webcam1/?action=stream
      name: Default
    - URL: http://192.168.1.44:8081/?action=stream
      isButtonEnabled: true
      name: Webcam 2

Another person has the same problem?

Thank you in advance,

**Comment by mikedmor** [comment]
Looks like for some reason your first webcam did not get the isButtonEnabled settings. If you add that onto the Default webcam everything should start working again for you. 

`multicam:
multicam_profiles:
- URL: /webcam1/?action=stream
isButtonEnabled: true
name: Default
- URL: http://192.168.1.44:8081/?action=stream
isButtonEnabled: true
name: Webcam 2`

0.2.1 was suppose to fix the data migration issue, but it still seems to be a problem, ill look into it some more and try to get another update to fix it. Please let me know if that solves your issues.

**Comment by mikedmor** [comment]
I just pushed 0.2.2. This should have a fix for the data migration issues. However it may reset you settings back to the new defaults. You may be able to avoid the reset if you add _config_version: 1 like the snipplet below before updating:

```
multicam:
    _config_version: 1
    multicam_profiles:
    - URL: /webcam1/?action=stream
       isButtonEnabled: true
       name: Default
    - URL: http://192.168.1.44:8081/?action=stream
       isButtonEnabled: true
       name: Webcam 2
```
